export const MODULE_METADATA = Symbol('MODULE_METADATA')
export const CONTROLLER_METADATA = Symbol('CONTROLLER_METADATA')
export const ROUTES_METADATA = Symbol('ROUTES_METADATA')
export const GUARDS_METADATA = Symbol('GUARDS_METADATA')
export const PIPES_METADATA = Symbol('PIPES_METADATA')
export const INTERCEPTORS_METADATA = Symbol('INTERCEPTORS_METADATA')
export const EXCEPTION_FILTERS_METADATA = Symbol('EXCEPTION_FILTERS_METADATA')

export const ROUTE_ARGS_METADATA = Symbol('ROUTE_ARGS_METADATA')
